import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin:
https://github.com/ultrapolar/polarxobsidian
*/
`;

const mode = process.argv[2];

// `node esbuild.config.mjs test` bundles the pure modules (no obsidian import)
// so node's built-in test runner can exercise them.
if (mode === "test") {
  await esbuild.build({
    entryPoints: ["src/render.ts", "src/notes.ts", "src/dates.ts"],
    bundle: true,
    format: "esm",
    target: "es2020",
    outdir: "test/bundle",
    outExtension: { ".js": ".mjs" },
    logLevel: "warning",
  });
  process.exit(0);
}

const prod = mode === "production";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
